import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("modifier select drops the native white box", () => {
  const css = readFileSync(new URL("./styles.css", import.meta.url), "utf8");
  const block = css.slice(css.indexOf("/* WebKitGTK paints a native white select"));
  assert.match(block, /\.field select \{[^}]*appearance:\s*none/s);
  assert.match(block, /-webkit-appearance:\s*none/);
  assert.match(block, /background-color:\s*#12121c/);
  assert.match(block, /\.field select option \{[^}]*background-color:\s*#12121c/s);
  assert.match(block, /color:\s*var\(--paper\)/);
});

test("avatars are translucent orbs with tunable glow", () => {
  const css = readFileSync(new URL("./styles.css", import.meta.url), "utf8");
  assert.match(css, /--avatar-radius:\s*50%/);
  assert.match(css, /--orb-glare-tint:\s*15%/);
  assert.match(css, /--orb-core-alpha:\s*0\.92/);
  assert.match(css, /--orb-glow-radius:\s*34px/);
  assert.match(css, /--orb-glow-alpha:\s*0\.28/);
  assert.match(css, /--orb-selected-glow-radius:\s*52px/);
  assert.match(css, /--orb-selected-glow-alpha:\s*0\.35/);
  assert.match(css, /--edge-pad:\s*calc\(var\(--orb-selected-glow-radius\) \+ 8px\)/);
  assert.match(css, /--panel-bg:\s*rgba\(7,\s*8,\s*28,\s*0\.76\)/);
  assert.match(css, /--panel-bg-solid:\s*rgba\(8,\s*8,\s*20,\s*0\.80\)/);
  assert.match(css, /--panel-blur:\s*18px/);
  assert.match(css, /\.bot-status::before \{[^}]*border-radius:\s*50%/s);
  assert.match(css, /backdrop-filter:\s*blur\(var\(--panel-blur\)\)/);
  assert.match(css, /@media \(prefers-reduced-motion:\s*reduce\)/);
  const pulse = css.slice(css.indexOf("@keyframes orb-pulse"), css.indexOf("@keyframes orb-busy"));
  assert.match(pulse, /transform:\s*scale\(1\.06\)/);
  assert.doesNotMatch(pulse, /box-shadow|filter:|blur\(/);
  const busy = css.slice(css.indexOf("@keyframes orb-busy"), css.indexOf("@media (prefers-reduced-motion"));
  assert.match(busy, /opacity:/);
  assert.doesNotMatch(busy, /box-shadow|filter:|blur\(/);
  assert.doesNotMatch(css, /\.bot-btn\.error \{[^}]*box-shadow/s);
  assert.doesNotMatch(css, /@keyframes bot-pulse/);
  const orb = css.slice(css.indexOf(".bot-btn {"), css.indexOf(".bot-btn::before"));
  assert.match(orb, /will-change:\s*opacity/);
  assert.match(orb, /contain:\s*layout style/);
  assert.doesNotMatch(orb, /box-shadow/);
  assert.match(css, /\.bot-btn::after,\s*\.active-avatar::after,\s*\.float-avatar::after \{[^}]*radial-gradient\(/s);
  const idleHalo = css.slice(css.indexOf(".bot-btn::after"), css.indexOf(".bot-btn.active::before"));
  assert.match(idleHalo, /var\(--orb-glare\)/);
  assert.match(idleHalo, /var\(--orb-core-alpha\)/);
  assert.match(idleHalo, /transparent 100%/);
  assert.match(idleHalo, /14%/);
  assert.match(idleHalo, /circle closest-side/);
  assert.doesNotMatch(idleHalo, /border-radius/);
  assert.doesNotMatch(idleHalo, /box-shadow|filter:|black/);
  assert.doesNotMatch(idleHalo, /--orb-selected-glow/);
  assert.match(css, /\.bot-btn\.active::after \{[^}]*radial-gradient\(/s);
  const selectedGlow = css.slice(css.indexOf(".bot-btn.active::after"), css.indexOf(".bot-btn.orb-enter::after"));
  assert.match(selectedGlow, /transparent 100%/);
  assert.match(selectedGlow, /inset:\s*calc\(-1 \* var\(--orb-selected-glow-radius\)\)/);
  assert.match(selectedGlow, /var\(--orb-selected-glow-alpha\)/);
  assert.match(selectedGlow, /14%/);
  assert.doesNotMatch(selectedGlow, /black|box-shadow|filter:/);
  assert.match(css, /\.bot-btn \{[^}]*border:\s*none/s);
  assert.match(css, /\.bot-btn \{[^}]*text-shadow:/s);
  assert.match(css, /\.bot-btn \.bot-label \{[^}]*text-shadow:/s);
  assert.match(css, /\.bot-btn \.bot-hit \{[^}]*inset:\s*-12px/s);
  assert.match(css, /\.bot-btn \.bot-hit \{[^}]*border-radius:\s*50%/s);
  assert.match(css, /\.active-avatar::before,\s*\.float-avatar::before \{[^}]*background:\s*none/s);
  assert.match(css, /\.center-panel\[hidden\]\s*\{[^}]*display:\s*none/s);
  assert.match(css, /\.center-panel \{[^}]*translateZ\(0\)/s);
  assert.doesNotMatch(css.slice(css.indexOf(".center-panel {"), css.indexOf(".center-panel::after")), /var\(--shadow\)/);
  assert.match(css, /html\.platform-linux \.center-panel[\s\S]*backdrop-filter:\s*none/);
  assert.doesNotMatch(css, /\.bot-btn\.active::before \{[^}]*animation:/s);
  assert.match(css, /\.bot-btn\.orb-enter::after,\s*\.bot-btn\.orb-enter\.busy::after \{[^}]*orb-pulse[^;]*\b2\b/s);
  assert.match(css, /html\.platform-linux \{[^}]*--panel-bg:\s*rgba\(7,\s*8,\s*28,\s*0\.90\)/s);
  assert.match(css, /html\.platform-linux \{[^}]*--panel-bg-solid:\s*rgba\(8,\s*8,\s*20,\s*0\.90\)/s);
});
